### ISSUE TITLE
Add to man page: time format for 'valid'

### ISSUE THREAD

**Issue by robertbruntz** [duncanmmacleod/ciecplib#131]
The man page for version 0.7.1 reports:
```
       -v VALID, -valid VALID, --valid VALID
              time requirement for proxy to be valid
```

It might be helpful for users to know what format(s) "VALID" can take - e.g., arbitrary number of seconds, HOURS:MINUTES, DAYS:HOURS:MINUTES:SECONDS, etc.  Note that the homologous line in `grid-proxy-info` was:
```
-valid HOURS:MINUTES, -v HOURS:MINUTES, -hours HOURS, -h HOURS
           Check that the proxy certificate is valid for at least HOURS hours and MINUTES minutes. If it is not, grid-proxy-info will exit with exit code 1.
```
but `ecp-cert-info` does not have the self-documenting `-hours` or `-h` options, which breaks drop-in compatibility.

(Unrelated: [PyPI page](https://pypi.org/project/ciecplib/) has that same page as the `Homepage`.  Just pointing that out in case that was unintentional, e.g., if the GitHub page should have been the home page.

**Comment by duncanmmacleod** [comment]
@robertbruntz, apologies for the delay in responding, comments inline below:

> * in `help`, should `-f` explanation say `(default: /tmp/x509up_u[actual user ID when I run it])`? or would `/tmp/x509up_u[UID]` be better? ('actual user ID when I run it' is taken from the environment in which it's run - [here](https://github.com/duncanmmacleod/ciecplib/blob/main/ciecplib/tool/ecp_cert_info.py#L90), but I didn't realize that when I ran it; I though it was some random UID hard-coded into the 'help' output)

I hope that for each, printing the absolute path that is the default is sensible, rather than abstracting things into a variable. I am hesitant to change this.

> * the [`-v` help](https://github.com/duncanmmacleod/ciecplib/blob/main/ciecplib/tool/ecp_cert_info.py#L98) should specify that the time should be input in HH:MM format

See #133.

> * the code should throw an explanatory error if `-v` is used without `-exists` (or `-e` or `--exists`)

In `ecp-cert-info` the `--valid` argument is not only used with `--exists`, so this doesn't really apply.

> * the [`-path` help](https://github.com/duncanmmacleod/ciecplib/blob/main/ciecplib/tool/ecp_cert_info.py#L163) is incorrect, in that it says `time left until certificate expires`, same as `-timeleft`, but should probably be something like `path to certificate file`

See #132.

> * it would probably be worth checking the help output from [the other `ciecplib` commands](https://github.com/duncanmmacleod/ciecplib/tree/main/ciecplib/tool) - `ecp-cookie-init` (?), `ecp-curl`, `ecp-get-cert`,       and `ecp-get-cookie`

Please open other tickets if you find specific issues that need to be addressed.

Thanks!
